### ISSUE TITLE
Build on top of other tool for output formats

### ISSUE THREAD

**Issue by lifelike** [lifelike/gamebookformat#1]
Too much of the work on gamebookformat goes into just formatting text and generating images, things that many other tools already do better. It would be better to focus on the gamebook-specific parts (numbering and shuffling sections, verifying links) and use some other formatting tool to handle all the low-level work of generating various output formats.

**Comment by Oreolek** [comment]
Maybe [Pandoc?](https://pandoc.org/)

**Comment by lifelike** [comment]
Yes, Pandoc is a tool I consider. Probably a format that Pandoc can use as input.

But I suspect Twine export (and graphs?) would still have to be implemented by essentially parsing the entire file and supporting all formatting markup it has.

So probably the simplest possible markup language that has good text editor support, a python library to parse it, and is supported by Pandoc. Preferably one that makes it possible to do things like inventory management and disabling some links without too many kludges.

**Comment by lifelike** [comment]
An alternative that would solve many/most/all issues would be to use a custom format but enforce a much stricter output style (possibly with a few different templates). Almost every gamebook use a format where there are no inline links in the text but rather just paragraphs of plain text followed by a list of possible branches to follow. That is also the most common form used in digital books. There are some exceptions to this, but the old/current gamebookformat (and other tools?) would still be around for that. With a much simpler structure like that it would be possible to feed everything to Pandoc for instance (and Twine) without too much code to maintain.

**Comment by lifelike** [comment]
I experimented with Pandoc a bit a few weeks ago and it looks very promising. With a very simple Lua filter a Markdown file can be processed to have numbered headers (all links and headers rewritten by the filter) and then output to a PDF or HTML or EPUB or other formats. Basically everything useful that gamebookformat does, other than the graphs. I think graphs can be done reasonably easily by outputting to JSON (that Pandoc also handles) and write an external script to turn that into a DOT file for GraphViz. The JSON-file can be used for checks similar to what gamebookformat does (look for sections that can not be reached etc).

My experimental filter does not shuffle the paragraphs, but not sure if that is a significant issue, and actually it is probably a more sane way to work with a gamebook anyway.

When I get around to post that as its own new project I will link to it from here and then symbolically close this issue.

**Comment by lifelike** [comment]
I experimented with Pandoc a bit a few weeks ago and it looks very promising. With a very simple Lua filter a Markdown file can be processed to have numbered headers (all links and headers rewritten by the filter) and then output to a PDF or HTML or EPUB or other formats. Basically everything useful that gamebookformat does, other than the graphs.

For graphs it should be possible to also use Pandoc and a Lua custom output format writer to generate a DOT file. The same feature can probably be abused to generate a report of unreachable paragraphs or unexpected endings etc.
http://lua.space/general/extending-pandoc-with-lua

My experimental filter does not shuffle the paragraphs, but not sure if that is a significant issue, and actually it is probably a more sane way to work with a gamebook anyway.

When I get around to post that as its own new project I will link to it from here and then symbolically close this issue.

**Comment by lifelike** [comment]
Posted a new repository with a Pandoc filter for gamebooks, which I think makes a lot more sense. There is not (yet?) any support for outputting graphs or sanity-checking books that gamebookformat can do, but it does number and shuffle paragraphs, and Pandoc has tons of features for taking care of everything else (outputs EPUB, PDF, HTML, DOCX, and many other file formats).

https://github.com/lifelike/pangamebook
