### ISSUE TITLE
Formatting Guide

### ISSUE THREAD

**Issue by nateProjects** [lifelike/gamebookformat#7]
Is there a guide to the gamebook markup format you are using anywhere?

I can see and get most of the information from the examples, but it would be helpful to have dedicated documentation.

**Comment by thedaniel** [comment]
Same question - is this actively developed? I'm working on a gamebook platform and was researching existing creation formats and of course this seems relevant

**Comment by lifelike** [comment]
It is not maintained. Sorry. There is more info in issue #1. Formatting is not documented. It never stabilized enough for that. Probably everything is covered by the examples though.

I made https://github.com/lifelike/pangamebook instead. I think that approach is much better. It is based on Pandoc and Pandoc has great documentation for all the formatting it supports (which is WAY more than what gamebookformat could do). It makes much more sense to use that and just have a small filter (e.g. pangamebook) to shuffle and number all the paragraphs and links, without trying to create a new formatting language like gamebookformat did.

If anyone else wants to maintain a fork of this they are of course welcome. :)

**Comment by thedaniel** [comment]
ah ok, clear. i'll check out pangamebook - thanks for the response!
